server:
    port: 8888
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
            max: 50
            min-spare: 5
    shutdown: graceful
spring:
    application:
        name: config-service
    lifecycle:
        timeout-per-shutdown-phase: 15s
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Cloud-Native-Spring-Project/config-repo
                    default-label: main
                    clone-on-start: true
                    timeout: 5
                    force-pull: true